@startuml
left to right direction

rectangle "ATM System" {
    usecase "Check Balances" as UC1
    usecase "Deposit Funds" as UC2
    usecase "Withdraw Cash" as UC3
    usecase "ATM Transaction" as UC4
    usecase "Customer Authentication" as UC5
    usecase "ATM Help" as UC6
}

UC1 --> UC4 : <<include>>
UC2 --> UC4 : <<include>>
UC3 --> UC4 : <<include>>
UC5 ..> UC4 : <<extend>>
UC6 ..> UC4 : <<extend>> : {Button.Help -> isPushed()}

note right of UC4
    Extension Points:
    - menu: provide help
end note
@enduml
